#pragma config(Motor,  port1,           arriereDroit,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           avantDroit,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           avantGauche,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           brasDownGauche, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           brasDownDroite, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           brasUpGauche,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           brasUpDroite,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           moteurCube,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           moteurPince,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          arriereGauche, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task testMoteur()
{
	motor[arriereDroit] = 100;
	wait1Msec(3000);
	motor[arriereDroit] = 0;

	motor[arriereGauche] = 100;
	wait1Msec(3000);
	motor[arriereGauche] = 0;

	motor[avantDroit] = 100;
	wait1Msec(3000);
	motor[avantDroit] = 0;

	motor[avantGauche] = 100;
	wait1Msec(3000);
	motor[avantGauche] = 0;

	motor[brasDownGauche] = 100;
	wait1Msec(3000);
	motor[brasDownGauche] = 0;

	motor[brasDownDroite] = 100;
	wait1Msec(3000);
	motor[brasDownDroite] = 0;

	motor[brasUpGauche] = 100;
	wait1Msec(3000);
	motor[brasUpGauche] = 0;

	motor[brasUpDroite] = 100;
	wait1Msec(3000);
	motor[brasUpDroite] = 0;

	motor[moteurCube] = 100;
	wait1Msec(3000);
	motor[moteurCube] = 0;

	motor[moteurPince] = 50;
	wait1Msec(1000);

	motor[moteurPince] = -50;
	wait1Msec(1000);
	motor[moteurPince] = 0;
}

task move()
{
	int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)

  while(1 == 1)
  {
  	if(vexRT[Btn5D] == 0)
  	{
	    joy_x = vexRT[Ch1];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
	    joy_y = vexRT[Ch2];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3'.

	    // Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
	    if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
	    {
	      motor[avantGauche]  = (joy_y + joy_x)/2;
	      motor[arriereGauche]  = (joy_y + joy_x)/2;
	      motor[avantDroit] = (joy_y - joy_x)/2;
	      motor[arriereDroit] = (joy_y - joy_x)/2;
	    }
	    // Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
	    else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
	    {
	      motor[avantGauche]  = (joy_y - joy_x)/2;
	      motor[arriereGauche]  = (joy_y - joy_x)/2;
	      motor[avantDroit] = (joy_y + joy_x)/2;
	      motor[arriereDroit] = (joy_y + joy_x)/2;
	    }
	    // Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
	    else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
	    {
	      motor[avantGauche]  = joy_x;
	      motor[arriereGauche]  = joy_x;
	      motor[avantDroit] = (-1 * joy_x);
	      motor[arriereDroit] = (-1 * joy_x);
	    }
	    // Standing still: (both abs(X) and abs(Y) are below the threshold)
	    else
	    {
	      motor[avantGauche]  = 0;
	      motor[arriereGauche]  = 0;
	      motor[avantDroit] = 0;
	      motor[arriereDroit] = 0;
	    }
	  }
  }
}

task moveArm()
{
	while(true)
	{
		if(vexRT[Btn8D] == 0 && vexRT[Btn5D] == 0)
		{
			motor[brasDownDroite] = vexRT[Ch3];
			motor[brasDownGauche] = vexRT[Ch3];
			motor[brasUpDroite] = vexRT[Ch3];
			motor[brasUpGauche] = vexRT[Ch3];
		}
		if(vexRT[Btn8D] == 1 && vexRT[Btn5D] == 0)
		{
			motor[brasDownDroite] = vexRT[Ch4];
			motor[brasDownGauche] = vexRT[Ch4];
			motor[brasUpDroite] = vexRT[Ch3];
			motor[brasUpGauche] = vexRT[Ch3];
		}
		if(vexRT[Btn8D] == 0 && vexRT[Btn5D] == 1)
		{
			motor[brasDownDroite] = vexRT[Ch2];
			motor[brasDownGauche] = vexRT[Ch2];
			motor[brasUpDroite] = vexRT[Ch3];
			motor[brasUpGauche] = vexRT[Ch3];
		}
	}
}

task moveCube()
{
	while(true)
	{
		if(vexRT[Btn6D] == 1)	 // if Btn6D is pressed:
		{
			motor[moteurCube] = 80;
		}
		if(vexRT[Btn6U] == 1)
		{
			motor[moteurCube] = -80;
		}
		if(vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0)
		{
			motor[moteurCube] = 0;
		}
	}
}

task movePince()
{
	while(true)
	{
		if(vexRT[Btn7D] == 1)	 // if Btn6D is pressed:
		{
			motor[moteurPince] = 80;
		}
		if(vexRT[Btn7L] == 1)
		{
			motor[moteurPince] = -80;
		}
		if(vexRT[Btn7D] == 0 && vexRT[Btn7L] == 0)
		{
			motor[moteurPince] = 0;
		}
	}
}

task main ()
{
  startTask(move);
  startTask(moveArm);
  startTask(moveCube);
  startTask(movePince);
  //startTask(testMoteur);
  while(true)
  {
  	wait1Msec(1);
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
